version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 3030:3030
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mysql:
    image: mysql:5.7.26
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=localuser
      - MYSQL_PASSWORD=localpass
      - MYSQL_DATABASE=local
  redis:
    image: redis:5.0.4-alpine
    ports:
      - 6379:6379
